@startmindmap
<style>
node {
    MaximumWidth 250
    FontSize 20
    BackgroundColor white
    LineColor black
}

rootNode {
    FontSize 30
    BackgroundColor lightgreen
}

:depth(1) {
    FontSize 25
    BackgroundColor lightblue
}

arrow {
    LineColor black
}
</style>

* Preface and Introduction

** What is business logic?
*** Business logic is all the loops and ‘if-else’ statements you need to implement the requirements

** The vast majority of software projects fail
*** Software crisis
*** Miscommunication

left side

** Tools
*** Strategic
**** Analyze business domains and strategy
**** Shared understanding of the business between the different stakeholders
**** Decomposing systems into components and defining their integration patterns
*** Tactical
**** Write code
***** reflects the business domain
***** addresses business goals
***** speaks the language of the business
@endmindmap
